use students;
CREATE TABLE STUDENTS (  ID INT NOT NULL,  NAME VARCHAR (20) NOT NULL,  AGE INT NOT NULL,  ADDRESS CHAR (25), USERID CHAR (25), PASSWORD CHAR (25), PRIMARY KEY (ID) );   
SELECT * FROM students;

SELECT * FROM students;

